# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 274611f5a8c99c3f7c203b317b887342cfd49fddf647396dd4308bd441c1c695dbb93ebb845ca7654574c2490d52349f993aa764620c72884e4f2361bcc7ac4b

test:
  secret_key_base: 2c4e795dc1b1d48ef7f2aeb4487555a8e11f08ecce428a8e50f5fe9f09a03240e226951c44c33dabe0be6ec7c0bff34296fd67ebc12971a6bb2917398ecd318a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
